## YAML Override template
## original/file.tpl: override/file.tpl
---
system/Zikula/Module/SearchModule/Resources/views/Block/search.tpl: themes/Zikula/Theme/ModernBusinessTheme/Resources/views/modules/ZikulaSearchModule/Block/search.tpl
system/Zikula/Module/BlocksModule/Resources/views/Block/Extmenu/topnav.tpl: themes/Zikula/Theme/ModernBusinessTheme/Resources/views/modules/ZikulaBlocksModule/Block/Extmenu/topnav.tpl
system/Zikula/Module/BlocksModule/Resources/views/Block/Extmenu/extmenu.tpl: themes/Zikula/Theme/ModernBusinessTheme/Resources/views/modules/ZikulaBlocksModule/Block/Extmenu/extmenu.tpl
system/Zikula/Module/BlocksModule/Resources/views/Block/Menutree/horizontal.tpl: themes/Zikula/Theme/ModernBusinessTheme/Resources/views/modules/ZikulaBlocksModule/Block/Menutree/horizontal.tpl
modules/News/templates/block/stories.tpl: themes/Zikula/Theme/ModernBusinessTheme/Resources/views/modules/News/block/stories.tpl
modules/News/templates/block/stories_row.tpl: themes/Zikula/Theme/ModernBusinessTheme/Resources/views/modules/News/block/stories_row.tpl